Repository chiefkikio/AFutureDate, pull requests merged in 2020-04, with the labels that each got.

#11 Converting div into header tag for better land mark support
  _includes/sidebar.html
Labels: WCAG

#8 Changing the content wrapper from a div into a main
  _layouts/default.html
Labels: WCAG

#15 Updating Main Tag, Updating H1 to support Main
  404.html
  _layouts/default.html
  _layouts/page.html
  _layouts/post.html
  index.html
Labels: ARIA, Fucus

#17 Allowing for mobile resize
  _includes/head.html
Labels: Mobile

#18 updating index to match wcag for other pages
  index.html
Labels: WCAG

#19 Adding region for related posts
  _layouts/post.html
Labels: WCAG

#16 Lb fix styles
  about.md
  public/css/hyde.css
  public/css/poole.css
Labels: WCAG

#20 Skip to css, Side bar css, other minor css changes
  _includes/sidebar.html
  _layouts/default.html
  index.html
  public/css/hyde.css
  public/css/poole.css
Labels: CSS, WCAG

#37 Adding Social Media to side bar. Adding a few social link for volenteers
  _includes/sidebar.html
  about.md
  public/css/hyde.css
  public/linkedIn.svg
  public/mail.svg
  public/twitter.svg
  public/youtube.svg
Labels: CSS, Images
